joy_node:
  deadzone: 0.01
  autorepeat_rate: 20
  coalesce_interval: 0.01

teleop:
  # Manual control is the default mode.
  # Holding any button enables autonomous control.
  ackermann:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input/teleop
    deadman_buttons: []
    axis_mappings:
      -
        axis: 1
        target: drive.speed
        scale: 2.0                   # joystick will command plus or minus 2 meters / second
        offset: 0.0
      -
        axis: 3
        target: drive.steering_angle
        scale: 0.34                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.0
