# Individual subscriber configuration:
#   name:           Source name
#   topic:          The topic that provides ackermann_cmd messages
#   timeout:        Time in seconds without incoming messages to consider this topic inactive
#   priority:       Priority: an UNIQUE unsigned integer from 0 (lowest) to MAX_INT 
#   short_desc:     Short description (optional)

subscribers:
  - name:        "Safety controller"
    topic:       "input/safety"
    timeout:     0.2
    priority:    15
    short_desc:  "Input for safety monitor, highest priority"
  - name:        "Teleoperation"
    topic:       "input/teleop"
    timeout:     0.2
    priority:    10
    short_desc:  "Input for human teleoperation (joystick)"
  - name:        "Autonomous navigation"
    topic:       "input/navigation"
    timeout:     0.2
    priority:    5
    short_desc:  "Input for autonomous navigation, lowest priority"
publisher:       "output"